name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/frontend
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./app/frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Debug Node.js and npm versions
        run: |
          echo "Node: $(node -v)"
          echo "npm: $(npm -v)"

      - name: Build frontend (if present)
        run: npm run build --if-present

      - name: Run Tests
        run: npm test
